
// File generated by noodle version O-2018.09#c3302020d9#181023, Tue Dec 18 09:47:44 2018
// Copyright 2014-2018 Synopsys, Inc. All rights reserved.
// C:\Synopsys\ASIP Programmer\O-2018.09-SP1\win64\bin\WINbin\noodle.exe -B -IC:/Synopsys/lpdsp32-v3_vO-2018.09_windows/lpdsp32-v3_vO-2018.09/lib -IC:/Synopsys/lpdsp32-v3_vO-2018.09_windows/lpdsp32-v3_vO-2018.09/lib/isg -IC:/Synopsys/lpdsp32-v3_vO-2018.09_windows/lpdsp32-v3_vO-2018.09/lib/runtime/include -D__tct_patch__=100 -ilpdsp32_chess.h +wRelease/chesswork main.c lpdsp32

.dir 0 "C:/Synopsys/lpdsp32-v3_vO-2018.09_windows/lpdsp32-v3_vO-2018.09/lib"
.text local 1 void_enable_interrupts
.src_ref 0 "lpdsp32_irq.h" 47
        ie = 1
.src_ref 0 "lpdsp32_irq.h" 48
        nop
